spring: 
  application:
    name: SCW-USER
  datasource:
    username: zhangsan
    password: 123456
    url: jdbc:mysql://39.106.91.206:3306/atcrowdfunding190513?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    filters: stat

  redis:
    host: 39.106.91.206
    port: 6379
    
server:
  port: 7000
 
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
 
eureka:
  client:
    service-url:
      defaultZone: http://39.105.47.96:8761/eureka/
  instance:
    appname: SCW-USER
    prefer-ip-address: true
 
swagger2: 
  enable: true

sms: 
  host: http://dingxin.market.alicloudapi.com
  path: /dx/sendSms
  method: POST
  appcode: 97c8ccac3fd5436a8e7ab5bbcc7c7498